### ISSUE TITLE
CLA

### ISSUE THREAD

**Issue by sjames** [sjames/cyclonedds-sys#6]
Hi @willstott101 ,

Thank you for the PRs into this project. Could you please review and sign the CLA for this project.  

The CLA text is at:  https://github.com/sjames/cyclonedds-sys/blob/master/CLA.md  (73fdee27f74e4d8e16fb4e603d427ad5908e1550)

Filling up the fololwing information in this ticket is considered to be the signature:

Date:
Name:
Title:
Address:

Thanks and regards,
Sojan

**Comment by willstott101** [comment]
Date: 9th Sept 2022
Name: William Stott
Title: Mr
Address: willstott101@gmail.com

**Comment by sjames** [comment]
Thank you @willstott101
